class CommonException(Exception):
    def __init__(self, message, code=-1,chi_msg="操作失败",need_warn=False):
        # Call the base class constructor with the parameters it needs
        super().__init__(message)
        # Now for your custom code...
        self.code = code
        self.chi_msg = chi_msg
        self.need_warn = need_warn

unknown_err = CommonException("unknown_err",10000,"未知错误")
no_login_err = CommonException("no_login_err",10400,"未登录")
req_format_err = CommonException("req_format_err",10401,"请求格式错误")
auth_err = CommonException("auth_err",10402,"认证或权限错误")
dup_err = CommonException("dup_err",10403,"重复操作")
login_err = CommonException("login_err",10404,"用户名或密码错误")
no_func_err = CommonException("no_func_err",10405,"请求方法不存在错误")
forbid_err = CommonException("forbid_err",10406,"禁止操作")
appinfo_err = CommonException("appinfo_err",10407,"缺少app信息")
req_param_err = CommonException("req_param_err",10408,"请求参数错误")
no_doc_err = CommonException("no_doc_err",10409,"没有符合条件的医生")
no_res_err = CommonException("no_res_err",10410,"未找到相关结果")
order_err = CommonException("order_err",10411,"订单异常")
num_err = CommonException("num_err",10412,"产品数量不够啦！")
phone_format_err = CommonException("phone_format_err",10413,"请填写您的电话，方便后续联系！")
order_depo_err = CommonException("order_depo_err",10414,"一次只允许一种订金类产品")
order_cate_diff_err = CommonException("order_cate_diff_err",10415,"一次只允许购买一类产品")
order_make_one_err = CommonException("order_make_one_err",10416,"一次只允许购买一件某种类下的同一种产品")
order_paying_err = CommonException("order_paying_err",10417,"请稍等，订单正在处理中")
order_one_prod_cate_err = CommonException("order_one_prod_cate_err",10418,"一次只允许购买某种类下的一种产品")
conn_order_err = CommonException("conn_order_err",10419,"关联订单失败")
conn_order_finish = CommonException("conn_order_finish",10420,"订单已关联")
freq_err = CommonException("freq_err",10421,"操作太频繁")
coupon_inval_err = CommonException("coupon_inval_err",10422,"优惠券已失效")
dzauth_err = CommonException("dzauth_err",10423,"dzauth_err")
too_short_15 = CommonException("too_short_15",10424,"7字喵言等你完成")
not_allow_review= CommonException("not_allow_review",10425,"订单消费完，才能评价哟")
groupbuy_part_num_err = CommonException("groupbuy_part_num_err",10426,"拼团人数错误")
groupbuy_part_num_full = CommonException("groupbuy_part_num_full",10427,"拼团人数已满")
groupbuy_auto_cancle_warn = CommonException("groupbuy_auto_cancle_warn",10428,"未成单的拼团，到期后会自动退款")
num10_err = CommonException("num10_err",10429,"亲，一次只能购买10个产品哈")
gb_order_not_pay_err = CommonException("gb_order_not_pay_err",10430,"您已参团，请去支付拼团订单")
gb_order_exist_err = CommonException("gb_order_exist_err",10431,"您已参团")
coupon_num_err = CommonException("coupon_num_err",10432,"优惠券只能购买一个产品")
gb_prod_num_err = CommonException("gb_prod_num_err",10433,"拼团只能购买一个产品")
date_err = CommonException("date_err",10434,"日期错误")
date_range_err = CommonException("date_range_err",10435,"日期跨度过大")
search_no_query_err = CommonException("search_no_query_err",10436,"请输入关键字")
miaobi_no_ok_err = CommonException("miaobi_no_ok_err",10437,"喵币不得和其他优惠混合使用")
user_limit_times_err = CommonException("user_once_err",10438,"该产品每个用户只能购买特定次数")
not_allow_reply_self = CommonException("not_allow_reply_self",10439,"不能回复自己哈")
content_weifa_err = CommonException("content_weifa_err",10440,"含有违规内容")
content_empty_err = CommonException("content_empty_err",10441,"不得为空")
no_gzh_err = CommonException("no_gzh_err",10442,'请先关注"巴喵"公众号哟')
no_openid_err = CommonException("no_openid_err",10443,'缺失openid')
gb_out_err = CommonException("gb_out_err",10444,'拼团已过期')
miaobi_no_enough_err = CommonException("miaobi_no_enough_err",10445,"喵币余额不足")